### ISSUE TITLE
Hours for FY21

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/forgeApp#14]
@Stefankirby, for the purpose of budgeting, approximately how many hours are meant for web services in FY '21 for this project? Grant's USGS project is asking for hundreds of hours and I want to make sure you get the amount of time you need for this project as well.

Thanks!

**Comment by Stefankirby** [comment]
Budget 140 hours for the year.  I will know more later in the summer concerning our actual budget breakout.
