### ISSUE TITLE
Application Review For Version 1.0 to be published

### ISSUE THREAD

**Issue by jjhi11** [UGS-GIO/forgeApp#15]
- [ ] Marshall Review

- [ ] Mike Hylland Review

**Comment by jjhi11** [comment]
@marshallrobinson Review issues #5 #6 #7 #9 #11

**Comment by marshallrobinson** [comment]
Overall, the app looks great. Here are a few things I think can be worked on to make it better. Some should probably be fixed before release, while others can probably wait for a later release.

-"FORGE Overview" panel needs reviewed by @geowomansteph 
-What is "Data Table" button for on some of the layers? (button appears, but it isn't functional)
-Can you add a button on each layer to "Zoom to Layer"?
-What are units on GW chem (and other layers that don't have units) legends?
-What are units in popups where there are missing units?
-Who is the audience for this application?
-Why are "Spring" and "others" Water Levels?
-All tooltips in popups say "Longitude" (at least the ones I could find)
-Are popups supposed to work for all layers? (for example, seismic data & geophysical data doesn't have popups)

Sorry these are all lumped together.

**Comment by Stefankirby** [comment]
I have added a table that lists the units for the fields in the geochem table.  It can be found at https://docs.google.com/spreadsheets/d/1irNteKugdJG2r7gSylNWutK4Q4MhzIJjGUZTdMi4_XQ/edit?usp=sharing

**Comment by marshallrobinson** [comment]
-Is it possible to hide the "Data Table" button for layers that do not have one? 
-When I click on the Data Table button for Geology, it only shows a couple units for me and there's a console TypeError "Cannot read property 'element' of undefined"

**Comment by marshallrobinson** [comment]
I'm moving the Data Table button to another issue and closing this issue.
