### ISSUE TITLE
Suggest static text edit

### ISSUE THREAD

**Issue by geowomansteph** [UGS-GIO/forgeApp#17]
**Use the space below (be very specific) to make a suggestion to any of the static text in the application.**
The Geology drop down menu thing

Are you suggesting an edit to text that already exists or proposing additional text?
Edits to text already there

What do you suggest the text says?
Several words are capitalized that shouldn't be.
1. Ground Crack, don't capitalize "crack"
2. Number 39, Porphyritic quartz latite, the last two words shouldn't be capitalized
3. Numbers 41 through 50 shouldn't all be caps, just first word
4.  number 51, "limestone" should be capitalized
5. Number 61, Howell Formations should be singular Formation
6. Number 64, "Gneiss" should not be capitalized
7. Number 66, "Schist" should not be capitalized

General comment: some of the descriptions are cut off by the box

After you propose new text, the Project Manager (Marshall) will have it reviewed by:
- [ ] Stephanie Carney
- [ ] Marshall Robinson

**Comment by jjhi11** [comment]
@marthajensen 

Could you take a look at these. I believe most are in the data. Thanks

**Comment by marthajensen** [comment]
@Stefankirby the changes listed in this thread are for the map legend in the application. I was wondering if you would like me to also edit the attribute tables to match the legend?

**Comment by marthajensen** [comment]
The edits in the map legend are done. This issue is ready for review @marshallrobinson
