### ISSUE TITLE
Question for Stefan

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/forgeApp#18]
@Stefankirby, I'm okay with how the app looks, but is there anyone else on the project team that you'd like to look at and/or review the app before it gets looked over by Bill and ultimately goes live on the Forge website?

**Comment by Stefankirby** [comment]
I think we are good when it is through Bill.

Thanks!

**Comment by marshallrobinson** [comment]
Ok, thanks. @Stefankirby, one more quick question before I move it up the review chain. The current title of the app says "Utah Geological Survey" (on the top bar next to the forge logo. Is this intentional or should that be changed to something else and give reference to UGS somewhere else on the app?

**Comment by Stefankirby** [comment]
That is intentional just to make sure it known who put it together.

**Comment by marshallrobinson** [comment]
@Stefankirby, what do you think of changing the text to the UGS logo, and then adding a more descriptive title of the application other than FORGE App?

**Comment by marshallrobinson** [comment]
Check out the title bar of this application for example: https://geology.utah.gov/apps/blm_mineral/

**Comment by Stefankirby** [comment]
That would be just fine

**Comment by marshallrobinson** [comment]
Last question....I think. Is there a timeline you need this all done by?

**Comment by jjhi11** [comment]
what should this new title be?

**Comment by marshallrobinson** [comment]
Maybe it doesn't need a title?

**Comment by Stefankirby** [comment]
Yes no title necessary Lets see what it looks like.  All of this can be done ASAP but not time critical>.....

**Comment by jjhi11** [comment]
Should be ready to go but the vpn isnt letting me connect to publish the new code

**Comment by Stefankirby** [comment]
Hey its veterans day we are not supposed to be working

**Comment by marshallrobinson** [comment]
It's been a long time since I have looked at this (sorry). 
"Utah Geological Survey" needs written out to the right of the UGS logo, and the "|" needs removed to the right of that if possible.

Look like this: 
![image](https://user-images.githubusercontent.com/5225390/101413889-54976f00-38a2-11eb-87b6-05e5b0171607.png)

Also, @Stefankirby, I think we've addressed this before but I'm not sure. Is the intention to publish this on only the Forge website or is the plan to also publish it on the UGS site?

**Comment by jjhi11** [comment]
this has been added

**Comment by marshallrobinson** [comment]
> Also, @Stefankirby, I think we've addressed this before but I'm not sure. Is the intention to publish this on only the Forge website or is the plan to also publish it on the UGS site?

Now that I have your attention (or I've annoyed you enough that you aren't answering-sorry again)...Did you have an answer for this question?

**Comment by Stefankirby** [comment]
This app will only be on the FORGE website.
