### ISSUE TITLE
Create database design/schema document

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/forgeApp#2]
Stefan and Martha need to set up database together.
Things to include in document:
- [ ] Database design
- [ ] Database name
- [ ] Relates/Joins 
- [ ] Field names
- [ ] Field types
- [ ] Domains (if any)
- [ ] Permissions
- [ ] Update schedule

Get final sign-off by Martha & post document to github.

**Comment by marthajensen** [comment]
I made a first attempt at this --Some things to notice are I combined Relates/Joins, Field Names, Field Types, and domains all into a section called Schema using pre-existing resources created before the Wiki page.  I also added a Workflow section and a re-direct to where the Data Services are located. Please comment and change it up if you want. I am open to different ideas for this-- this is my first stab and what I think this document might look like.

https://github.com/UGS-GIO/forgeApp/wiki/Database-design-(schema)-document
