### ISSUE TITLE
Review by Bill K.

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/forgeApp#25]
@bkeach2 this application is ready for you to review when you have time. Thanks!

https://geology.utah.gov/apps/jay/tests/FORGE/

**Comment by bkeach2** [comment]
Found some time today to review. In the successive posts are comments about each category:
1) Infrastructure - due to scale, really hard to see the Field Office. Should the map 'scale up' so that the user can see the outline when the object is selected?

**Comment by bkeach2** [comment]
2) Geology - not sure what Zoom to layer does. After selecting, nothing happened. Same is true under other options.

**Comment by bkeach2** [comment]
3) Geology - Data Table, brought up a table with a single entry, for hornblende. I was confused.

**Comment by bkeach2** [comment]
4) Subsurface Geologic Data - nothing displayed when selecting Milford Valley Top of Bedrock Surface. No data table, nothing happens when selection Zoom to Layer.

**Comment by bkeach2** [comment]
5) Thermal Data - a. Are you contouring the data? or Just using contour maps provided by FORGE? Reason I ask, is that it is obvious the contouring has not been done properly. End result is that it challenges the credibility of the map.

**Comment by bkeach2** [comment]
6. Thermal Data - b. The contours in Yellow on 'Isotherms at 1km depth' are difficult to see. Please use a darker color.

**Comment by bkeach2** [comment]
7) Seismicity – I’m confused by the legend. Should the first entry be understood to mean all earthquakes less than or equal to M 6.627542? Or just those between 2.5 and 6.627542? Also, not sure you need that many decimal places for this type of map. Suggest using the same number of decimal places for all of the ranges.

**Comment by bkeach2** [comment]
7) Geophysical data
There is a symbol but no label for two of the three categories. See image below.

**Comment by bkeach2** [comment]
9) Groundwater – Water Geochemistry - No data table. No explanation of the label at each location. Well name?

**Comment by jjhi11** [comment]
> 1. Geophysical data
>    There is a symbol but no label for two of the three categories. See image below.

Add data table to this layer

**Comment by jjhi11** [comment]
> 1. Groundwater – Water Geochemistry - No data table. No explanation of the label at each location. Well name?

Add data table for this layer

**Comment by marthajensen** [comment]
Issues addressed in latest data update:
6. I darkened the yellow symbol for the Isotherms at 1km 
7. The Seismicity 1850 to 2016 legend has been revised to one decimal point and the <sign has been replaced with a range of values
8. I added labels to the Geophysical data in the Legend. @jjhi11 please remove the title bar for FORGE gravity points and  geophysical benchmarks

**Comment by marthajensen** [comment]
8. The legend didn't look right with labels instead of headings. Therefore, the headings (i.e. Geophysical Benchmarks and FORGE gravity points) are still there. I added the text "Location" next to the symbol in the Legend instead.
