### ISSUE TITLE
Fix GIS attributes and create GIS gdb for download 

### ISSUE THREAD

**Issue by marthajensen** [UGS-GIO/forgeApp#29]
All of the GIS data in the app needs to be available for download. 

To do:
Create zipped gdb of GIS data-- using the same organization method and naming scheme as the legend in the application

**Comment by marthajensen** [comment]
@Stefankirby  I made a GIS dataset for the web application that the user can download. In the gdb, I renamed many of the datasets to match the web app datasets. For example, the dataset "Utah_EQcat_1850_2016" was renamed "Seismicity_1850_to_2016" to match the name of the dataset in the web application. I recorded all of the renamed feature classes in this [Google Sheet](https://docs.google.com/spreadsheets/d/1L08-Q6R9zkxUgdXK01s0BNM2TKx4Bw5O1NTjV2ONSZQ/edit#gid=358871440). Dataset name changes are on Sheet 3 - "GIS locations and tracking naming scheme"), columns D and I (current name, name in downloadable gdb)

When I created this dataset, I also revised the data you asked me to from the email on 14-Jun-21 (shown below). The text was replaced in the downloadable version as well as in the web app version. 

------------------------------------------------------------------------------------------------------------------------------------------

Hi Martha,

Hope you are well.  

At a recent meeting it came up that the FORGE webmap may contain some outdated names in the geologic unit descriptions.

We need to remove and change any instance's of "N. Mag fault" or "Negro Mag Wash" and change these to the "Mag Lee fault" or "Mag Lee Wash".  I found these in the Granite Dikes unit descriptions but we need to check all the fields of the geologic map for these.

Can you search these out and change these as necessary?  And then repost the edits to the webmap?

Thanks,

Stefan

------------------------------------------------------------------------------------------------------------------------------------------


The following units - Granite Dikes, Qaf3 and Qaf 2 all had "Negro Mag Wash" in the description field. I replaced the text with "Mag Lee Fault."  Give the website a few hours to update with the text changes - the underlying data is updated, but sometimes it takes a while for the updated data to show on the website. 


Attached is the downloadable gdb. If you see any issues with it, please let me know. 

[FORGE_data.gdb.zip](https://github.com/UGS-GIO/forgeApp/files/6656026/FORGE_data.gdb.zip)

**Comment by marthajensen** [comment]
@jjhi11 
The FORGE zipped gdb is ready for the app. It is located at \\168.180.168.181\geology\html\apps\forge\appfiles\FORGE_data.gdb.zip

I will update the symbology of well 56-32 today (as indicated in the email below). 

Email from Stefan on 21-June-21 for our records: 

OK it looks like the gdb is just fine.  I didn't look at every layer but the ones I did look at looked good.

Could we add the data download button to the pancake menu in the upper left hand corner?

Also we need to update the status of the 56-32 well to existing (should be symbolized black).  I will get the drilled depth and track info so it can be added in 3-d.

Thanks

Stefan

**Comment by marthajensen** [comment]
The symbol for well 56-32 has been changed to black

**Comment by jjhi11** [comment]
@Stefankirby What should the download data panel say? For example this is what the Mineral App has.

![CaptureMinerals](https://user-images.githubusercontent.com/27784116/122962861-0da32f80-d343-11eb-8665-cffeb5abb909.JPG)

**Comment by Stefankirby** [comment]
FORGE Geoscientific Webmap Data (Download)
Data download contains all GIS layers used to construct the webmap as a zipped .gdb file.
For questions concerning this download or the individual data layers please contact Stefan Kirby stefankirby@utah.gov.

**Comment by jjhi11** [comment]
@marshallrobinson this has been added in the latest commit. could you please review?

**Comment by marshallrobinson** [comment]
This all looks good to me, thanks everyone. Feel free to close it when ready.
